### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by MissKalani** [SungamR/hammars-produktion#3]
Vad använder du Github för? Skriv dina issues i din dagbok :calendar: :sleeping:

**Comment by SungamR** [comment]
Haha... Jag kollade faktiskt ifall jag kunde få folk att använda Github issues för våra interna förbättringsmöten istället för fucking sharepoint!  Resultatet blev iofs bara att ingen använder något av dem, detta tycks bara vara för oss :neckbeard:s

**Comment by MissKalani** [comment]
Vi försökte stalka lite koder från dina repo men du verkar ha gömt dem någonstans :-1:  :1234:

**Comment by SungamR** [comment]
Jag gör inget värt att visa omvärlden :no_entry:
